name: plan_it
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # firebase 
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  firebase_app_check: ^0.2.1+18
  cloud_firestore: ^4.15.9

  # font
  google_fonts: ^6.2.1

  # icon
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6

  # utils
  provider: ^6.1.2
  flashy_tab_bar2: ^0.0.10
  flutter_overlay_loader: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
